name: EthriaHoe
main: de.leahcimkrob.ethriahoe.EthriaHoe
version: ${project.version}
api-version: 1.20
softdepend: [PlotSquared, Worldguard]
author: Bloody_Mind
description: Toggle ItemFrame properties (fixed/visible) with a hoe.

commands:
  ethriahoe:
    description: Hauptbefehl für EthriaHoe
    permission: ethriahoe.admin

permissions:
  ethriahoe.admin:
    description: "erlaubt das reloaden der Confdig"
    default: op
  ethriahoe.toggle:
    description: "Erlaubt die Nutzung der EthriaHoe auf allen Plots (auch fremde)"
    default: op
  ethriahoe.toggleFixed:
    description: "Erlaubt das Umschalten des Fixed-Status von Rahmen mit der Hoe"
    default: op
  ethriahoe.toggleVisible:
    description: "Erlaubt das Umschalten der Sichtbarkeit von Rahmen mit der Hoe"
    default: op
